apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mvplwamkl-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:a2568df139fa0dbd3430336bfb33f74d9ebbb257@sha256:0347125c8a72d4de5fbf3635429cd31267e7804c14ed720b3eb1a1e4e4ee24ff
          name: container-image
